import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useQuery } from "@tanstack/react-query";
import { CardList } from "@/components/Card/CardList";
import { Loading } from "@/components/Loading";
import { useFetcher } from "../components/common/hooks/useFetcher";
import { withDataCheck } from "@/components/common/hocs/withDataCheck";
import { CardInterface } from "@/components/Card/card.types";
import { handlerFavorite } from "@/components/common/utils/localStorageUtils";
import { useFavoriteStorage } from "@/components/common/hooks/useFavoriteStorage";
import { pickProperties } from "@/components/common/utils/propertyUtils";
import { PICKED_KEYS } from "@/components/common/constants/cardConstants";

const inter = Inter({ subsets: ["latin"] });

const EnhancedCardList = withDataCheck(CardList);

const Home = () => {
  const { favorites, setFavorites } = useFavoriteStorage();

  const { data: fetchCatList } = useFetcher();
  const { data: fetchCatImage } = useFetcher();
  const { isLoading, error, data } = useQuery<CardInterface[]>({
    queryKey: ["catList"],
    queryFn: async () => {
      const catList: CardInterface[] = await fetchCatList(
        "breeds?limit=4&page=0"
      );
      const newCatList = pickProperties(catList, PICKED_KEYS);
      const catsWithImages = await Promise.all(
        newCatList.map(async (cat: any): Promise<CardInterface> => {
          const image = await fetchCatImage("images", cat.reference_image_id);
          return { ...cat, imageUrl: image.url };
        })
      );
      return catsWithImages;
    },
  });
  console.log("datatatatataat", data);

  const handleFavoritesList = (cardData: CardInterface) => {
    handlerFavorite(cardData, favorites, setFavorites);
  };

  if (isLoading) return <Loading />;
  if (error) return "An error has occurred: " + error.message;

  return (
    <>
      <Head>
        <title>Cat Land</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <EnhancedCardList
          cardData={data ?? []}
          handleFavorite={handleFavoritesList}
        />
      </main>
    </>
  );
};

export default Home;
